# Copyright (c) 2014, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

Import('gateway_env')

gateway_env['GWMA_DISTDIR'] = gateway_env['DISTDIR'] + '/gatewayMgmtApp'

gateway_env.Append(LIBPATH = '$GWMA_DISTDIR/lib');
gateway_env.Append(CPPPATH = '$GWMA_DISTDIR/inc');

gateway_env.Install('$GWMA_DISTDIR/inc/alljoyn/gateway', gateway_env.Glob('inc/alljoyn/gateway/*.h'))
gateway_env.Install('$GWMA_DISTDIR/bin', gateway_env.SConscript('src/SConscript', exports = ['gateway_env']))
gateway_env.Install('$GWMA_DISTDIR/bin', File('manifest.xsd'))
gateway_env.Install('$GWMA_DISTDIR/bin', File('installPackage.sh'))
gateway_env.Install('$GWMA_DISTDIR/bin', File('removePackage.sh'))
gateway_env.Install('$GWMA_DISTDIR/bin', File('defaultConfig.xml'))

# Build docs
installDocs = gateway_env.SConscript('docs/SConscript', exports = ['gateway_env'])
gateway_env.Depends(installDocs, gateway_env.Glob('$GWMA_DISTDIR/inc/alljoyn/gateway/*.h'));
