#******************************************************************************
# Copyright (c) 2013, AllSeen Alliance. All rights reserved.
#
#    Permission to use, copy, modify, and/or distribute this software for any
#    purpose with or without fee is hereby granted, provided that the above
#    copyright notice and this permission notice appear in all copies.
#
#    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
#    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
#    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#*****************************************************************************

Import('gateway_env')
import os

gateway_env.Append(CPPPATH = ['$LIBXML2_BASE'])
gateway_env.Append(LIBS = ['libxml2'])
gateway_env.Prepend(LIBS = ['alljoyn_about', 'alljoyn_services_common'])

srcs = gateway_env.Glob('*.cc')
srcs.extend(gateway_env.Glob('busObjects/*.cc'))    
srcs.extend(gateway_env.Glob('app/*.cc'))
objs = gateway_env.Object(srcs)

prog = gateway_env.Program('GatewayManagementApp', objs)

Return('prog')
